simple_theme <- theme_bw() + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

theme_option_1 <- theme(plot.title = element_text(face = "bold",
                                                  size = rel(1), hjust = 0.5),
                        plot.subtitle=element_text(face = "bold",hjust = 0.5, size=13,vjust=1),
                        text = element_text(),
                        panel.background = element_rect(colour = 'NA'),
                        plot.background = element_rect(colour = NA),
                        panel.border = element_blank(), 
                        axis.title = element_text(face = "bold",size = rel(1)),
                        axis.title.y = element_text(angle=90,vjust =2),
                        axis.title.x = element_text(vjust = -0.2),
                        axis.text = element_text(), 
                        axis.line = element_line(colour="black",size=0.5),
                        axis.ticks = element_line(),
                        panel.grid.major = element_blank(),
                        panel.grid.minor = element_blank(),
                        legend.key = element_rect(colour = NA),
                        legend.position = "bottom",
                        legend.direction = "horizontal",
                        legend.key.size= unit(0.3, "cm"),
                        legend.title = element_text(face="italic"),
                        plot.margin=unit(c(10,5,5,5),"mm"),
                        strip.background=element_rect(colour="#f0f0f0",fill="#f0f0f0"),
                        strip.text = element_text(face="bold"))